version: "3.7"
services:
  database:
    image: postgres
    container_name: database_telzir
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=loldesign
      - POSTGRES_DB=telzir
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: telzir
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata: